services:
  postgresql:
    image: postgres
    container_name: library_postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
  kafka:
    container_name: library_kafka
    image: apache/kafka:latest
    volumes:
      - kafka:/data/kafka
    ports:
      - "9092:9092"
volumes:
  postgres:
  kafka: