server:
  port: 8080
  servlet:
    context-path: /library

spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/library
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/library
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER}
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver
  config:
    import: file:.env[.properties]
  kafka:
    consumer:
      group-id: library
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      max-poll-records: 250 #controls the amount of records in batches
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        order_updates: true
        jdbc:
          batch_size: 50
kafka:
  topic:
    - library

springdoc:
  swagger-ui:
    doc-expansion: none
    path: /swagger-ui.html
    tags-sorter: alpha
    syntax-highlight:
      activated: true
      theme: agate
    try-it-out-enabled: true
logging:
  level:
    org:
      springframework:
#        transaction:
#          interceptor: trace
        security: info
    web: info
    liquibase: info